### ISSUE TITLE
Regime Shift Index different 

### ISSUE THREAD

**Issue by Wolf35988** [alexhroom/rshift#11]
Hello and thank you very much for the package.
I am trying to replicate the results obtained by Rodionov in its 2004 paper doi:10.1029/2004GL019448 (the same reported in the manual) using the PDO timeseries. Many years ago, when this package was not yet available, I wrote my own R code for the regime shift detection algorithm, and I successfully got the same graph of the paper:

figure from the 2004 article:
![Rodionov2004](https://github.com/alexhroom/rshift/assets/140265229/59cb5c93-bc6e-4459-9860-c0736847331c)

graph from my code:
![myalgotirhm](https://github.com/alexhroom/rshift/assets/140265229/e0432ecd-0e80-453d-93f9-42eb52470725)
So they are exactly the same.

Using your function "Rodionov" with the same inputs (l=10, prob=0.95), I got this instead:
![rshift](https://github.com/alexhroom/rshift/assets/140265229/1121c758-8199-415d-a5d0-e6084e6ba595)

that is, the same temporal indication (expect the 2003 which is missing), but the values of the RSI are a bit different...
How can you explain this? Are there updates with respect to the 2004 article? Thank you!

I attach also the input file:
[Time_Series PDO.txt](https://github.com/alexhroom/rshift/files/12136806/Time_Series.PDO.txt)

**Comment by alexhroom** [comment]
@Wolf35988 thanks for flagging this up, and especially for providing the input data! I will do some tweaking to try and get your values - I would certainly prefer consistency between STARS implementations.

I did test rshift on a PDO file to try and emulate Rodionov's data but i think my data looked a little different for some reason. there's a little mathematical rigour missing in how STARS is defined in the paper, which can lead to discrepancies in how 'sensitive' the algorithm is - luckily (as you provided) this is very unlikely to create a hypothesis-affecting difference! I have some ideas of where the difference comes from in this case (for the missing 2003 indication, this is simply because I'd originally written it to not analyse the last *l* values of the data, as this means in *any case* where the final data point is significantly different, it will always be recognised as a regime shift even when it may well be an outlier!)
